name: r-dsci-200
channels:
  - conda-forge
  - r 
  - nodefaults
dependencies:
  - jupyter-resource-usage
  - jupyterlab-git
  - jupyterlab_rise
  - nbgitpuller
  - pexpect=4.9.0
  - python=3.12.*
  - pyzmq=27.0.2
  - r-arrow
  - r-base
  - r-caret
  - r-corrr
  - r-crayon
  - r-devtools
  - r-digest
  - r-dmwr2
  - r-dplyr
  - r-e1071
  - r-forecast
  - r-gridextra
  - r-hexbin
  - r-hmisc
  - r-htmltools
  - r-htmlwidgets
  - r-httr
  - r-infer
  - r-irkernel
  - r-jsonlite
  - r-kknn
  - r-matrixstats
  - r-mice
  - r-mlmetrics
  - r-naniar
  - r-nycflights13
  - r-palmerpenguins
  - r-randomforest
  - r-rcurl
  - r-rmarkdown
  - r-robotstxt
  - r-rodbc
  - r-rsqlite
  - r-rvest
  - r-stringr
  - r-testthat
  - r-themis
  - r-tibble
  - r-tidymodels
  - r-tidyverse
  - r-vim
  - r-visdat
  - r-waffle
  - unixodbc
